import pandas as pd
import pypsa
import matplotlib.pyplot as plt

# Load data
df_elec = pd.read_csv('data/electricity_demand.csv', sep=';', index_col=0) # in MWh
df_elec.index = pd.to_datetime(df_elec.index) #change index to datatime

df_onshorewind = pd.read_csv('data/onshore_wind_1979-2017.csv', sep=';', index_col=0)
df_onshorewind.index = pd.to_datetime(df_onshorewind.index)

df_offshorewind = pd.read_csv('data/offshore_wind_1979-2017.csv', sep=';', index_col=0)
df_offshorewind.index = pd.to_datetime(df_offshorewind.index)

df_solar = pd.read_csv('data/pv_optimal.csv', sep=';', index_col=0)
df_solar.index = pd.to_datetime(df_solar.index)

# Chosen country of interest
country='DNK'


# Initialize network model 
network = pypsa.Network()
hours_in_2015 = pd.date_range('2015-01-01 00:00Z', '2015-12-31 23:00Z', freq='h')
network.set_snapshots(hours_in_2015.values)
network.add("Bus", "electricity bus")

# add load to the bus
network.add("Load", "load", bus="electricity bus", p_set=df_elec[country].values)

network.loads_t.p_set

def annuity(n,r):
    """ Calculate the annuity factor for an asset with lifetime n years and discount rate  r """
    if r > 0:
        return r/(1. - 1./(1.+r)**n)
    else:
        return 1/n

# add the different carriers, only gas emits CO2
network.add("Carrier", "gas", co2_emissions=0.19) # in t_CO2/MWh_th
network.add("Carrier", "onshorewind")
network.add("Carrier", "offshorewind")
network.add("Carrier", "solar")
network.add("Carrier", "battery storage")

# add onshore wind generator
CF_wind = df_onshorewind[country][[hour.strftime("%Y-%m-%dT%H:%M:%SZ") for hour in network.snapshots]]
capital_cost_onshorewind = annuity(27,0.07)*1118775 # has been updated
network.add("Generator", "Onshore wind", bus="electricity bus", p_nom_extendable=True, carrier="onshorewind", capital_cost = capital_cost_onshorewind, marginal_cost = 0, p_max_pu = CF_wind.values)

# add offshore wind generator
CF_wind_off = df_offshorewind[country][[hour.strftime("%Y-%m-%dT%H:%M:%SZ") for hour in network.snapshots]]
capital_cost_offshorewind = annuity(27,0.07)*2115944 # has been updated
network.add("Generator", "Offshore wind", bus="electricity bus", p_nom_extendable=True, carrier="offshorewind", capital_cost = capital_cost_offshorewind, marginal_cost = 0, p_max_pu = CF_wind_off.values)

# add solar PV generator
CF_solar = df_solar[country][[hour.strftime("%Y-%m-%dT%H:%M:%SZ") for hour in network.snapshots]]
capital_cost_solar = annuity(25,0.07)*450000 # has been updated
network.add("Generator", "Solar", bus="electricity bus",p_nom_extendable=True, carrier="solar", capital_cost = capital_cost_solar, marginal_cost = 0, p_max_pu = CF_solar.values)

# add OCGT (Open Cycle Gas Turbine) generator
capital_cost_OCGT = annuity(25,0.07)*453960  # has been updated
fuel_cost = 30 # €/MWh
efficiency_OCGT = 0.41 # MWh_e/MWh
marginal_cost_OCGT = fuel_cost/efficiency_OCGT # in €/MWh_e
network.add("Generator", "OCGT", bus="electricity bus", p_nom_extendable=True, carrier="gas", capital_cost = capital_cost_OCGT, marginal_cost = marginal_cost_OCGT)

# add CCGT
capital_cost_CCGT = annuity(25,0.07)*880000  # has been updated
fuel_cost = 30 # €/MWh
efficiency_CCGT = 0.56 # MWh_e/MWh
marginal_cost_CCGT = fuel_cost/efficiency_CCGT # in €/MWh_el
network.add("Generator", "CCGT", bus="electricity bus", p_nom_extendable=True, carrier="gas", capital_cost = capital_cost_CCGT, marginal_cost = marginal_cost_CCGT)


network.generators_t.p_max_pu  

# Solve the model (optimize the system)
network.optimize(solver_name='gurobi',solver_options={"OutputFlag": 0,"LogToConsole": 0})

# Objective value
print(network.objective/1000000) #in 10^6 €
print(network.objective/network.loads_t.p.sum()) # EUR/MWh

#optimal capacities of the generators
print(network.generators.p_nom_opt.div(1e3))

# Total energy generated by each generator
print(network.generators_t.p.sum().div(1e6))


################################################
##########      Plotting results      ##########
################################################
import matplotlib.pyplot as plt

labels = ['Onshore wind', 'Offshore wind', 'Solar PV', 'Gas (OCGT)', 'Gas (CCGT)']
model_names = ['Onshore wind', 'Offshore wind', 'Solar', 'OCGT', 'CCGT']
colors=['blue', 'dodgerblue', 'orange', 'crimson', 'darkviolet']

# Plotting installed capacities as pie chart
cap_sizes = [network.generators.p_nom_opt[name] for name in model_names]
plt.figure(figsize=(6,5), dpi=300)
plt.pie(cap_sizes, colors=colors, labels=[f'{label}\n{size/1000:.1f} GW' for label, size in zip(labels, cap_sizes)], wedgeprops={'linewidth':0})
plt.axis('equal')
plt.title('Installed capacity mix', y=1.05, fontweight='bold')
plt.tight_layout()
plt.savefig('1a_installed_capacity_mix.png', dpi=300)
plt.show()

# Delete item from list if its optimal capacity is zero to avoid plotting it
for index,name in enumerate(model_names):
    if network.generators.p_nom_opt[name]==0:
        del model_names[index]
        del labels[index]
        del colors[index]

# Plotting generation time series for the first week of January 2015
plt.figure(figsize=(8,5),dpi=300)
plt.plot(network.loads_t.p['load'][0:168], color='grey', label='Demand',lw=4)
for index,name in enumerate(model_names):
    plt.plot(network.generators_t.p[name][0:168], color=colors[index], label=labels[index])
plt.ylabel('Generation [MWh/h]')
plt.title('Electricity generation first week on January 2015')
plt.xlabel('Time')
plt.xlim(network.snapshots[0], network.snapshots[167])
plt.xticks(rotation=45)
plt.legend(fancybox=True, shadow=True, loc='best')
plt.tight_layout()
plt.savefig('1a_timeseries_winter.png', dpi=300)
plt.show()

# Ploting generation time series for the first week of July 2015
plt.figure(figsize=(8,5),dpi=300)
plt.plot(network.loads_t.p['load'][4344:4512], color='grey', label='Demand',lw=4)
for index,name in enumerate(model_names):
    plt.plot(network.generators_t.p[name][4344:4512], color=colors[index], label=labels[index])
plt.ylabel('Generation [MWh/h]')
plt.title('Electricity generation first week on July 2015')
plt.xlabel('Time')
plt.xlim(network.snapshots[4344], network.snapshots[4511])
plt.xticks(rotation=45)
plt.legend(fancybox=True, shadow=True, loc='best')
plt.tight_layout()
plt.savefig('1a_timeseries_summer.png', dpi=300)
plt.show()


# Plotting generation mix as pie chart
sizes = [network.generators_t.p[name].sum() for name in model_names]
percentages = [size/sum(sizes)*100 for size in sizes]
plt.figure(figsize=(6,5),dpi=300)
plt.pie(sizes, colors=colors, labels=[f'{label}\n{percentage:.1f}%' for label, percentage in zip(labels, percentages)],  wedgeprops={'linewidth':0})
plt.axis('equal')
plt.title('Annual electricity generation mix',y=1.05, fontweight='bold')
plt.tight_layout()
plt.savefig('1a_annual_generation_mix.png', dpi=300)
plt.show()

# Plotting duration curve of the generation for each technology
plt.figure(figsize=(8,5), dpi=300)
for index,name in enumerate(model_names):
    sorted_generation = network.generators_t.p[name].sort_values(ascending=False).reset_index(drop=True)
    plt.plot(sorted_generation, label=labels[index], color=colors[index],lw=3)
plt.ylabel('Generation [MWh/h]')
plt.title('Duration curve of generation')
plt.xlabel('Hours')
plt.legend(fancybox=True, shadow=True, loc='best')
plt.tight_layout()
plt.savefig('1a_duration_curve.png', dpi=300)
plt.show()

# Plotting standardized duration curve (CFs) of the generation for each technology
plt.figure(figsize=(8,5), dpi=300)
for index,name in enumerate(model_names):
    sorted_generation = network.generators_t.p[name].sort_values(ascending=False).reset_index(drop=True)/network.generators.p_nom_opt[name]
    plt.plot(sorted_generation, label=labels[index], color=colors[index],lw=3)
plt.ylabel('CF')
plt.title('Duration curve of generation')
plt.xlabel('Hours')
plt.legend(fancybox=True, shadow=True, loc='best')
plt.tight_layout()
plt.savefig('1a_duration_curve_CFs.png', dpi=300)
plt.show()



###################################################
######    (c)  Add storage  #######
###################################################

labels = ['Onshore wind', 'Offshore wind', 'Solar PV', 'Gas (OCGT)', 'Gas (CCGT)', 'Battery storage']
model_names = ['Onshore wind', 'Offshore wind', 'Solar', 'OCGT', 'CCGT', 'battery storage']
colors=['blue', 'dodgerblue', 'orange', 'crimson', 'darkviolet', 'lightgreen']


# adding the new units
network.add(
    "StorageUnit",
    "battery storage",
    bus="electricity bus",
    carrier="battery storage",
    max_hours=2,
    capital_cost= annuity(20,0.07)*2*288000,
    efficiency_store=0.98,
    efficiency_dispatch=0.97,
    p_nom_extendable=True,
    cyclic_state_of_charge=True,
)

# Solve the model (optimize the system)
network.optimize(solver_name='gurobi',solver_options={"OutputFlag": 0,"LogToConsole": 0})


# df with the optimal capacities of the generators AND storage unit
optimal_capacities = network.generators.p_nom_opt.copy()
for name in network.storage_units.index:
    optimal_capacities[name] = network.storage_units.p_nom_opt[name]

# Plotting installed capacities as pie chart
cap_sizes = [optimal_capacities[name] for name in model_names]
plt.figure(figsize=(6,5), dpi=300)
plt.pie(cap_sizes, colors=colors, labels=[f'{label}\n{size/1000:.1f} GW' for label, size in zip(labels, cap_sizes)], wedgeprops={'linewidth':0})
plt.axis('equal')
plt.title('Installed capacity mix', y=1.05, fontweight='bold')
plt.tight_layout()
plt.savefig('1c_installed_capacity_mix.png', dpi=300)
plt.show()

# Battery storage stackplot
fig, ax = plt.subplots(figsize=(10, 3))

# In order to create a stackplot we need to separate the positive and negative parts, using the clip method.
bat_dis = network.storage_units_t.p.clip(lower=0)  # positive: discharge
bat_ch  = network.storage_units_t.p.clip(upper=0)  # negative: charging

# Note that p > 0 in a bus means injection into the bus (i.e. generation or in this case discharge from the battery into the bus).

# Stack renewables + battery discharge together above 0
renewables = network.generators_t.p[['Onshore wind', 'Offshore wind', 'Solar']].sum(axis=1).rename("Renewables")
supply = pd.concat([
    bat_dis.rename(columns={"battery storage": "Battery discharge"}),
    renewables.to_frame("Renewables"),
], axis=1)
supply.plot.area(ax=ax, linewidth=0, stacked=True,
                 color=["#2ca02c", "#1f77b4"])

# Battery charging below 0 (separate call is fine here — it naturally starts from 0 and goes negative)
bat_ch.rename(columns={"battery storage": "Battery charge"}).plot.area(
    ax=ax, linewidth=0, stacked=True, color=["#ff7f0e"])

# Demand (constant)
network.loads_t.p_set.sum(axis=1).plot(ax=ax, color="black", linestyle="--", label="Demand")

ax.axhline(0, color="black", linewidth=0.5)
ax.set_ylabel("MW")
ax.set_ylim(-200, 1200)
ax.legend(frameon=False, bbox_to_anchor=(1.05, 1))
plt.tight_layout()
plt.savefig('1c_battery_stackplot.png', dpi=300)
plt.show()